Repository siriusdevs/homeworks_23, pull requests merged in 2023-10, with the labels that each got.

#11 Inozemtsev
  hw1.py
  test_hw1.py
Labels: ready

#6 Vasilenko
  hw1.py
  test_hw1.py
Labels: ready

#12 Grigoryan
  hw1.py
  test_hw1.py
Labels: ready

#8 Eremin
  .gitignore
  hw1.py
  setup.cfg
  task_1
  test_hw1.py
Labels: ready

#14 ARSENOVICH
  hw1.py
  setup.cfg
  test_hw1.py
  text1
Labels: ready, dreadful commits

#2 Ozornin
  hw1.py
  test_hw1.py
Labels: ready, dreadful commits

#26 add homeworks_list.py
  homeworks_list.py
  requirements.txt
Labels: enhancement

#10 👀 Added a solution for the first homework - Dyatlova
  hw1.py
  setup.cfg
  test_hw1.py
Labels: ready

#13 Tatarnikov
  hw1.py
  setup.cfg
  test_hw1.py
Labels: ready

#16 Demyanenko
  .github/workflows/pylint.yml
  hw1.py
  setup.cfg
  task_1
  test_hw1.py
Labels: ready, dreadful commits

#18 Litvinov
  hw1.py
  setup.cfg
  task_1
  test_hw1.py
Labels: ready

#25 Tarasov
  hw1.py
  test_hw1.py
Labels: ready, dreadful commits

#17 Tyurin
  hw1.py
  setup.cfg
  test_hw1.py
Labels: ready

#19 Nikiforov
  hw1.py
  setup.cfg
  test_hw1.py
Labels: ready

#30 Коренякин А.
  hm1.py
  setup.cfg
  task_1
  test_hm1.py
Labels: ready, dreadful commits

#33 Nudga
  .github/workflows/pylint.yml
  hw1.py
  task_1
  test_hw1.py
Labels: ready

#24 Zagora
  hw1.py
  setup.cfg
  test_hw1.py
Labels: ready, dreadful commits
