Repository siriusdevs/homeworks_23, pull requests merged in 2023-12, with the labels that each got.

#42 Grigoryan
  .github/workflows/pylint.yml
  hw2.py
  hw2/expected/1.json
  hw2/expected/10.json
  hw2/expected/11.json
  hw2/expected/2.json
  hw2/expected/3.json
  hw2/expected/4.json
  hw2/expected/5.json
  hw2/expected/6.json
  hw2/expected/7.json
  hw2/expected/8.json
  hw2/expected/9.json
  hw2/input/1.json
  hw2/input/10.json
  hw2/input/11.json
  hw2/input/2.json
  hw2/input/3.json
  hw2/input/4.json
  hw2/input/5.json
  hw2/input/6.json
  hw2/input/7.json
  hw2/input/8.json
  hw2/output/1.json
  hw2/output/10.json
  hw2/output/11.json
  hw2/output/2.json
  hw2/output/3.json
  hw2/output/4.json
  hw2/output/5.json
  hw2/output/6.json
  hw2/output/7.json
  hw2/output/8.json
  hw2/output/9.json
  task_2
  test_hw2.py
Labels: ready, dreadful commits

#49 Romodanov hw2
  .github/workflows/pylint.yml
  dataset_hw2/__file_for_testing__.json
  dataset_hw2/first.json
  dataset_hw2/second.json
  dataset_hw2/third.json
  hw2/data_hw2.json
  hw2/increment_field.py
  hw2/main.py
  hw2/new.json
  hw2/test_hw2.py
  hw2/test_increment_field.py
  hw2/test_transform_stats.py
  hw2/transform_stats.py
  task_2
Labels: ready

#54 Komarov hw2
  .github/workflows/pylint.yml
  .gitignore
  hw2/__init__.py
  hw2/const_hw2.py
  hw2/fields_hw2.py
  hw2/hw2.py
  hw2/main.py
  hw2/test_data/complex.json
  hw2/test_data/empty.json
  hw2/test_data/example.json
  hw2/test_data/invalid_date.json
  hw2/test_data/invalid_json.json
  hw2/test_data/missing_age.json
  hw2/test_data/missing_last_login.json
  hw2/test_hw2.py
  hw2/types_hw2.py
  hw2/unreal_hw2.py
Labels: ready, unreal, комаров

#68 Nudga
  hw2/expected_folder/1.json
  hw2/expected_folder/10.json
  hw2/expected_folder/11.json
  hw2/expected_folder/2.json
  hw2/expected_folder/3.json
  hw2/expected_folder/4.json
  hw2/expected_folder/5.json
  hw2/expected_folder/6.json
  hw2/expected_folder/7.json
  hw2/expected_folder/8.json
  hw2/expected_folder/9.json
  hw2/hw2.py
  hw2/module_hw2.py
  hw2/test_hw2.py
  hw2/tests_folder/output.json
  hw2/tests_folder/test1.json
  hw2/tests_folder/test10.json
  hw2/tests_folder/test11.json
  hw2/tests_folder/test2.json
  hw2/tests_folder/test3.json
  hw2/tests_folder/test4.json
  hw2/tests_folder/test5.json
  hw2/tests_folder/test6.json
  hw2/tests_folder/test7.json
  hw2/tests_folder/test8.json
  hw2/tests_folder/test9.txt
Labels: ready

#62 Eremin HW2
  .github/workflows/pylint1.yml
  .github/workflows/pylint2.yml
  hw1/hw1.py
  hw1/task_1
  hw1/test_hw1.py
  hw2/data_hw2.json
  hw2/hw2.py
  hw2/task_2
  hw2/test_hw2.py
  hw2/tests/test_data.json
  pyproject.toml
  setup.cfg
  test_hw1.py
Labels: ready

#63 Inozemtsev hw2
  .github/workflows/pylint.yml
  .gitignore
  hw2/data_file/data_file_1.json
  hw2/data_file/data_file_2.json
  hw2/data_file/data_file_3.json
  hw2/generate_stats.py
  hw2/hw2.py
  hw2/make_dir.py
  hw2/open_file.py
  hw2/test_answer/answer_test_1.json
  hw2/test_answer/answer_test_2.json
  hw2/test_answer/answer_test_3.json
  hw2/test_answer/answer_test_4.json
  hw2/test_hw2.py
  hw2/test_result/test_1.json
  hw2/test_result/test_2.json
  hw2/test_result/test_3.json
  hw2/test_result/test_4.json
Labels: ready

#46 Demyanenko
  .github/workflows/pylint.yml
  hw1/hw1.py
  hw1/task_1
  hw1/test_hw1.py
  hw2/files/data_hw2.json
  hw2/files/empty.json
  hw2/files/example.json
  hw2/files/example2.json
  hw2/files/example_error.json
  hw2/files/test_data_hw2.json
  hw2/hw2.py
  hw2/out.json
  hw2/task_2
  hw2/test_hw2.py
  task_2
Labels: ready

#69 Kuznetsova hw1
  .github/workflows/pylint.yml.save
  hw1.py
  test_hw1.py
Labels: ready

#38 Kolkareva
  .github/workflows/pylint.yml
  .github/workflows/pylint.yml.save
  data_hw2.json
  hw1.py
  task_1
  task_2
  test_hw1.py
Labels: ready, dreadful commits

#79 Nikiforov HW2
  .github/workflows/pylint.yml
  hw1/hw1.py
  hw1/task_1
  hw1/test_hw1.py
  hw2/consts_hw2.py
  hw2/exceptions_hw2.py
  hw2/hw2.py
  hw2/task_2
  hw2/test_hw2.py
  hw2/tests/empty.json
  hw2/tests/incorrect_data.json
  hw2/tests/invalid_format.json
  hw2/tests/no_age.json
  hw2/tests/no_last_login.json
  hw2/tests/normal.json
  hw2/tests/normal2.json
Labels: ready

#80 zagora hw3
  .github/workflows/pylint 3.yml
  hw2/output_file.json
  hw3/hw3.py
  hw3/task_3
  hw3/test_hw3.py
  setup.cfg
Labels: ready

#82 hw3
  hw3.py
  task_1
  test_hw3.py
Labels: dreadful commits

#55 Kristev HW1
  hw1.py
  task_2
  test_hw1.py
Labels: ready, dreadful commits

#64 Druzhinin HW1
  hw1.py
  test_hw1.py
Labels: ready

#56 Trofimov hw_1
  .github/workflows/pylint.yml
  .github/workflows/pylint.yml.save
  hw1.py
  test_hw1.py
Labels: ready, dreadful commits

#88 complete hw1
  .github/workflows/pylint.yml
  hw1.py
  task_1
  test_hw1.py
Labels: dreadful commits

#74 Tarasov
  .github/workflows/pylint.yml
  hw2/ages_operations.py
  hw2/app_exceptions.py
  hw2/data_2.json
  hw2/data_hw2.json
  hw2/hui.json
  hw2/hw2.py
  hw2/test_data_hw2/age_is_not_found.json
  hw2/test_data_hw2/data_hw2_0.json
  hw2/test_data_hw2/data_hw2_1.json
  hw2/test_data_hw2/data_hw2_2.json
  hw2/test_data_hw2/data_hw2_3.json
  hw2/test_data_hw2/data_hw2_4.json
  hw2/test_data_hw2/directory_error.json
  hw2/test_data_hw2/no_such_file_directory.json
  hw2/test_data_hw2/output_hw2_0.json
  hw2/test_data_hw2/output_hw2_1.json
  hw2/test_data_hw2/output_hw2_2.json
  hw2/test_data_hw2/output_hw2_3.json
  hw2/test_data_hw2/output_hw2_4.json
  hw2/test_data_hw2/some_text.txt
  hw2/test_data_hw2/t.json
  hw2/test_data_hw2/test_output_0.json
  hw2/test_data_hw2/test_output_1.json
  hw2/test_data_hw2/test_output_2.json
  hw2/test_data_hw2/test_output_3.json
  hw2/test_data_hw2/wrong.json
  hw2/test_data_hw2/wrong_data.json
  hw2/test_hw2.py
  hw2/user_statistic.py
  setup.cfg
  task_2
Labels: ready

#78 Litvinov HW2
  .github/workflows/pylint.yml
  hw1/hw1.py
  hw1/task_1
  hw1/test_hw1.py
  hw2/data_hw2.json
  hw2/hw2.py
  hw2/requirements.txt
  hw2/task_2
  hw2/test_data/negative/invalid_age_type.json
  hw2/test_data/negative/invalid_age_value.json
  hw2/test_data/negative/invalid_date.json
  hw2/test_data/positive/empty.json
  hw2/test_data/positive/example.json
  hw2/test_data/positive/missing_age.json
  hw2/test_data/positive/missing_last_login.json
  hw2/test_hw2.py
  task_2
Labels: ready

#71 Krdyan HW2
  .github/workflows/pylint.yml
  hw1/hw1.py
  hw1/task_1
  hw1/test_hw1.py
  hw2/const.py
  hw2/hw2.py
  hw2/task_2
  hw2/test_data/complex/input.json
  hw2/test_data/complex/output.json
  hw2/test_data/empty/input.json
  hw2/test_data/empty/output.json
  hw2/test_data/simple/input.json
  hw2/test_data/simple/output.json
  hw2/test_hw2.py
  hw2/user_statistics.py
  setup.cfg
  task_2
Labels: ready

#86 Dyatlova - HW3
  .github/workflows/pylint.yml
  homework1/hw1.py
  homework1/test_hw1.py
  homework3/hw3.py
  homework3/test_participant.py
  homework3/test_project.py
  homework3/test_task.py
  homework3/test_team.py
  setup.cfg
Labels: ready

#92 Noskov Michael HW_1
  .github/workflows/pylint.yml
  .gitignore
  hw1.py
  test_hw1.py
Labels: ready

#89 Blagodarova HW1
  .github/workflows/pylint.yml
  hw1.py
  test_hw1.py
Labels: ready

#93 Demyanenko HW3
  .github/workflows/pylint.yml
  hw3/hw3.py
  hw3/test_hw3.py
  setup.cfg
Labels: ready

#73 Zorina A.
  .github/workflows/pylint.yml
  hw2.py
  hw2/expected/1.json
  hw2/expected/10.json
  hw2/expected/11.json
  hw2/expected/2.json
  hw2/expected/3.json
  hw2/expected/4.json
  hw2/expected/5.json
  hw2/expected/6.json
  hw2/expected/7.json
  hw2/expected/8.json
  hw2/expected/9.json
  hw2/input/1.json
  hw2/input/10.json
  hw2/input/11.json
  hw2/input/2.json
  hw2/input/3.json
  hw2/input/4.json
  hw2/input/5.json
  hw2/input/6.json
  hw2/input/7.json
  hw2/input/8.json
  hw2/input/9.json
  hw2/output/1.json
  hw2/output/10.json
  hw2/output/2.json
  hw2/output/3.json
  hw2/output/4.json
  hw2/output/5.json
  hw2/output/6.json
  hw2/output/7.json
  hw2/output/8.json
  hw2/output/9.json
  task_2.txt
  test_hw2.py
Labels: ready

#85 Kuznetsova hw2
  .github/workflows/pylint.yml
  data_hw2.json
  hw1/hw1.py
  hw1/task_1
  hw1/test_hw1.py
  hw2/files_for_tests/DATA/data1_hw2.json
  hw2/files_for_tests/DATA/data2_hw2.json
  hw2/files_for_tests/DATA/data3_hw2.json
  hw2/files_for_tests/DATA/data_hw2.json
  hw2/files_for_tests/EXPECTED/expected.json
  hw2/files_for_tests/EXPECTED/expected1.json
  hw2/files_for_tests/EXPECTED/expected2.json
  hw2/files_for_tests/EXPECTED/expected3.json
  hw2/files_for_tests/RESULT/result.json
  hw2/files_for_tests/RESULT/result1.json
  hw2/files_for_tests/RESULT/result2.json
  hw2/files_for_tests/RESULT/result3.json
  hw2/hw2.py
  hw2/task_2
  hw2/test_hw2.py
Labels: ready

#84 Komarov HW3
  .github/workflows/pylint.yml
  hw3/__init__.py
  hw3/aviacompany.py
  hw3/flight.py
  hw3/hw3.py
  hw3/passenger.py
  hw3/tests/__init__.py
  hw3/tests/test_aviacompany.py
  hw3/tests/test_aviacompany_aggregation.py
  hw3/tests/test_flight.py
  hw3/tests/test_hw3.py
  hw3/tests/test_passenger.py
  hw3/tests/test_ticket.py
  hw3/ticket.py
  setup.cfg
Labels: ready, комаров

#72 Korenyakin A. hw2
  .github/workflows/pylint.yml
  .github/workflows/pylint.yml.save
  hw1.py
  hw2/data_hw2.json
  hw2/hw2.py
  hw2/result.json
  hw2/static_city.py
  hw2/static_last_login.py
  hw2/test_data/empty_file.json
  hw2/test_data/result_1.json
  hw2/test_data/result_2.json
  hw2/test_data/result_3.json
  hw2/test_data/test_1.json
  hw2/test_data/test_2.json
  hw2/test_data/test_3.json
  hw2/test_data/test_invalid_date.json
  hw2/test_hw2.py
  result.json
  task_2
  test_hw1.py
Labels: ready

#94 Roganov HW2
  .github/workflows/pylint.yml
  .gitignore
  hw1/hw1.py
  hw1/task_1
  hw1/test_hw1.py
  hw2/consts.py
  hw2/errors.py
  hw2/hw2.py
  hw2/json_parsing.py
  hw2/src/expected/empty.json
  hw2/src/expected/example.json
  hw2/src/expected/simple.json
  hw2/src/inputs/empty.json
  hw2/src/inputs/example.json
  hw2/src/inputs/invalid_format.json
  hw2/src/inputs/missing_year.json
  hw2/src/inputs/nothing.json
  hw2/src/inputs/simple.json
  hw2/src/invalid_path.json
  hw2/src/outputs/empty.json
  hw2/src/outputs/example.json
  hw2/src/outputs/simple.json
  hw2/task_2
  hw2/test_hw2.py
  hw3/task_3
  task_2
Labels: ready

#91 Otroschenko_hw1
  .github/workflows/pylint.yml
  hw1.py
  hw3.py
  task_1
  task_3
  test_hw1.py
  test_hw3.py
Labels: ready

#96 Nudga HW3
  hw3/hw3.py
  hw3/module_hw3.py
  hw3/test_hw3.py
  setup.cfg
Labels: ready, unreal

#103 Inozemtsev HW3
  .github/workflows/pylint.yml
  hw3/hw3.py
  hw3/test_hw3.py
  setup.cfg
Labels: ready

#115 Tarasov hw3
  .github/workflows/pylint.yml
  hw3/dish.py
  hw3/product.py
  hw3/restaurant.py
  hw3/test_hw3.py
  setup.cfg
Labels: ready

#75 Romodanov hw3
  .github/workflows/pylint.yml
  hw3/course/course.py
  hw3/course/test/test_course.py
  hw3/course_with_participants/course_with_participants.py
  hw3/course_with_participants/test/test_course_with_participants.py
  hw3/courses_participant/courses_participant.py
  hw3/courses_participant/test/test_courses_participant.py
  hw3/person/person.py
  hw3/person/test/test_person.py
  hw3/student/student.py
  hw3/teacher/teacher.py
  pytest.ini
  setup.cfg
  task_3
Labels: help wanted, ready

#130 Safronova's hw3
  hw_3/hw3.py
  hw_3/test_hw3.py
  task_1
  task_2
Labels: dreadful commits

#105 Krdyan HW3
  .github/workflows/pylint.yml
  data_hw2.json
  hw3/__init__.py
  hw3/hw3.py
  hw3/task_3
  hw3/test_hw3.py
  setup.cfg
Labels: ready, dreadful commits, unreal

#116 Blagodarova HW3
  .github/workflows/pylint.yml
  hw1/hw1.py
  hw1/task_1
  hw1/test_hw1.py
  hw2/data_hw2.json
  hw2/task_2
  hw3/hw3.py
  hw3/task_3
  hw3/test_hw3.py
  setup.cfg
Labels: ready

#126 Tyurin HW3
  .github/workflows/pylint.yml
  hw3/hw3.py
  hw3/test_hw3.py
Labels: ready

#120 Kolkareva HW3
  .github/workflows/pylint.yml
  hw3/hw3.py
  hw3/test_hw3.py
  setup.cfg
  task_3
Labels: ready

#127 Litvinov hw3
  .github/workflows/pylint.yml
  hw3/hw3.py
  hw3/task_3
  hw3/test_hw3.py
  setup.cfg
Labels: ready

#119 Noskov Misha HW_3
  .github/workflows/pylint.yml
  hw3.py
  setup.cfg
  test_hw3.py
Labels: ready

#100 Krivenko_hw1
  .github/workflows/pylint.yml
  data_hw2.json
  hw1.py
  hw3.py
  task_3
  test_hw1.py
Labels: dreadful commits

#66 Pazych hw1
  .github/workflows/pylint.yml
  hw1.py
  setup.cfg
  test_hw1.py
Labels: halfway

#132 Turapov_hw1
  .github/workflows/pylint.yml
  hw1/hw1.py
  hw1/task_1
  hw1/test_hw1.py
Labels: ready

#148 Argun HW1
  .github/workflows/pylint.yml
  hw1/hw1.py
  hw1/test_hw1.py
Labels: ready

#142 Nehoroshev HW3
  .github/workflows/pylint.yml
  data_hw2.json
  hw3.py
  task_1
  task_2
  test_hw3.py
Labels: ready

#113 Dyatlova - HW2
  .github/workflows/pylint.yml
  hw1/hw1.py
  hw1/test_hw1.py
  hw2/hw2.py
  hw2/test_hw2.py
  hw2/tests/expected/1.json
  hw2/tests/expected/2.json
  hw2/tests/expected/3.json
  hw2/tests/expected/4.json
  hw2/tests/expected/5.json
  hw2/tests/expected/6.json
  hw2/tests/input/1.json
  hw2/tests/input/2.json
  hw2/tests/input/3.json
  hw2/tests/input/4.json
  hw2/tests/input/5.json
  hw2/tests/input/6.json
  hw2/tests/output/1.json
  hw2/tests/output/2.json
  hw2/tests/output/3.json
  hw3/hw3.py
  hw3/test_participant.py
  hw3/test_project.py
  hw3/test_task.py
  hw3/test_team.py
  task_2
Labels: ready

#53 Danilov_hw1
  data_hw2.json
  hw1/hw1.py
  hw1/task_1
  hw1/test_hw1.py
  task_2
Labels: ready

#146 Korenyakin A hw3
  .github/workflows/pylint.yml
  hw2/static_last_login.py
  hw2/test_data/result_2.json
  hw3/member.py
  hw3/project.py
  hw3/task.py
  hw3/team.py
  hw3/test_error_hw3.py
  hw3/test_hw3.py
  setup.cfg
Labels: ready
