Repository siriusdevs/homeworks_23, pull requests merged in 2023-11, with the labels that each got.

#31 Malanin
  .github/workflows/pylint.yml
  hw1.py
  hw2/data_hw2.json
  hw2/task_2
  setup.cfg
  task_2
  test_hw1.py
Labels: ready

#37 Telegin
  hw1.py
  setup.cfg
  test_hw1.py
Labels: ready, dreadful commits

#47 Komarov
  .gitignore
  hw1.py
  setup.cfg
  test_hw1.py
Labels: ready

#51 Osipov
  .github/workflows/pylint.yml
  .github/workflows/pylint.yml.save
  .gitignore
  hw1.py
  setup.cfg
  test_hw1.py
Labels: ready

#45 zorina_e
  hw1.py
  test_hw1.py
Labels: suspicious, ready

#43 Vasilenko
  .github/workflows/pylint.yml
  .gitignore
  data_hw2.json
  hw2/README.md
  hw2/__init__.py
  hw2/hw2.py
  hw2/src/bbtypes.py
  hw2/src/enums.py
  hw2/src/schemas.py
  hw2/src/utils/__init__.py
  hw2/src/utils/common.py
  hw2/src/utils/initialize_test_data.py
  hw2/src/utils/user_stats.py
  hw2/src/utils/validate_data_file.py
  hw2/test_files/expected_output/1.json
  hw2/test_files/expected_output/10.json
  hw2/test_files/expected_output/11.json
  hw2/test_files/expected_output/2.json
  hw2/test_files/expected_output/3.json
  hw2/test_files/expected_output/4.json
  hw2/test_files/expected_output/5.json
  hw2/test_files/expected_output/6.json
  hw2/test_files/expected_output/7.json
  hw2/test_files/expected_output/8.json
  hw2/test_files/expected_output/9.json
  hw2/test_files/input/1.json
  hw2/test_files/input/10.json
  hw2/test_files/input/11.1.json
  hw2/test_files/input/2.json
  hw2/test_files/input/3.json
  hw2/test_files/input/4.json
  hw2/test_files/input/5.json
  hw2/test_files/input/6.json
  hw2/test_files/input/7.json
  hw2/test_files/input/8.json
  hw2/test_files/input/9.json
  hw2/test_files/last_modification_date
  hw2/test_files/output/1.json
  hw2/test_files/output/10.json
  hw2/test_files/output/11.json
  hw2/test_files/output/2.json
  hw2/test_files/output/3.json
  hw2/test_files/output/4.json
  hw2/test_files/output/5.json
  hw2/test_files/output/6.json
  hw2/test_files/output/7.json
  hw2/test_files/output/8.json
  hw2/test_files/output/9.json
  hw2/test_hw2.py
  requirements.txt
  setup.cfg
Labels: ready
